### ISSUE TITLE
New Gist JS / CSS Feature -- Add Rule

### ISSUE THREAD

**Issue by Aetherinox** [thomiceli/opengist#223]
Hey,

The newest CSS / JS feature for gists is great. I've almost got it integrated, however, I noticed a rule that is missing in the gist CSS which Github Gists do use.

It is related to IFRAME

**Github Gist CSS**
```css
.gist iframe.render-viewer {
	width: 100%;
	height: 480px;
	overflow: hidden;
	border: 0
}
```

**OpenGist CSS**
```css
.opengist-embed audio,
.opengist-embed canvas,
.opengist-embed embed,
.opengist-embed iframe,
.opengist-embed img,
.opengist-embed object,
.opengist-embed svg,
.opengist-embed video {
	display: block;
	vertical-align: middle
}
```

When I integrate the code into my Obsidian vault, I can actually see my Gist in a widget, however, the iframe is not set to 100%.

---

Here is a few screenshots to show how it presently looks:

**OpenGist Gist Example**
![1](https://github.com/thomiceli/opengist/assets/118329232/d572feac-66a9-48eb-bea6-054ebca4afe5)

And this is how it looks if I use a Github Gist:

**Github Gist Example**
![2](https://github.com/thomiceli/opengist/assets/118329232/0e5706fa-086f-4ad0-9f75-7386d2d37b08)

**Comment by Aetherinox** [comment]
Sorry, one more addition. The scrollbar when integrated is right up on the paste, and makes it especially hard to work with if you have a single line that is scrollable.

If there's any way to add a padding (or whatever you deem looking better).

```css
.opengist-embed :is(:where(.dark) .dark\:border-gray-800) {
    padding-bottom: 20px;
}
```

Is the CSS class I used with inspect element
