### ISSUE TITLE
Internal Server Error when adding TOTP

### ISSUE THREAD

**Issue by m4skedbyte** [thomiceli/opengist#406]
Attempting to set up a TOTP code for a local account results in a `500 Internal Server Error`.

The following error message is shown in the log:
```
opengist  | 08:23:38 INF internal/web/server.go:195 HTTP duration=7.255641 ip=<removed> method=GET status=200 uri=/settings/totp/generate
opengist  | 08:23:58 ERR internal/web/auth.go:638 Cannot store TOTP secret error="crypto/aes: invalid key size 64"
```
![image](https://github.com/user-attachments/assets/b20781fa-5c7a-42bc-9de6-dde3c0f37f10)

![image](https://github.com/user-attachments/assets/e720a450-90a3-4f77-8da6-9bfd3671e4aa)

The following `compose.yml` was used during the test:
```yml
---
services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.8
    container_name: opengist
    restart: unless-stopped
    ports:
      - "127.0.0.1:6157:6157" # HTTP port
      - "2222:2222"
    environment:
      - UID=1000
      - GID=1000
      - OG_INDEX_ENABLED=true
      - OG_GIT_DEFAULT_BRANCH=master
      - OG_SECRET_KEY=<removed>
      - OG_LOG_LEVEL=debug
    volumes:
      - opengist_data:/opengist

volumes:
  opengist_data:
```
